name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version Bump Type (patch, minor, major)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # Ensure we can push back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      - name: Configure Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version
        working-directory: ./packages/rin
        run: npm version ${{ inputs.version_type }}

      - name: Build Framework
        run: pnpm run build

      - name: Publish to NPM
        working-directory: ./packages/rin
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Version Update to Main
        run: |
          git push origin main --follow-tags
